In [1]:
import pandas as pd

In [2]:
train= pd.read_csv('/content/train.tsv', delimiter= '\t')
train.head()

url  ...  label
0  http://www.bloomberg.com/news/2010-12-23/ibm-p...  ...      0
1  http://www.popsci.com/technology/article/2012-...  ...      1
2  http://www.menshealth.com/health/flu-fighting-...  ...      1
3  http://www.dumblittleman.com/2007/12/10-foolpr...  ...      1
4  http://bleacherreport.com/articles/1205138-the...  ...      0

[5 rows x 27 columns]

In [3]:
train

url  ...  label
0     http://www.bloomberg.com/news/2010-12-23/ibm-p...  ...      0
1     http://www.popsci.com/technology/article/2012-...  ...      1
2     http://www.menshealth.com/health/flu-fighting-...  ...      1
3     http://www.dumblittleman.com/2007/12/10-foolpr...  ...      1
4     http://bleacherreport.com/articles/1205138-the...  ...      0
...                                                 ...  ...    ...
7390  http://techcrunch.com/2010/09/08/kno-raises-46...  ...      0
7391  http://www.uncoached.com/category/why-i-miss-c...  ...      0
7392  http://eatthis.menshealth.com/slide/sweet-pota...  ...      1
7393                          http://naturallyella.com/  ...      1
7394  http://sportsillustrated.cnn.com/2011_swimsuit...  ...      0

[7395 rows x 27 columns]

In [4]:
train.isnull().sum()

url                               0
urlid                             0
boilerplate                       0
alchemy_category                  0
alchemy_category_score            0
avglinksize                       0
commonlinkratio_1                 0
commonlinkratio_2                 0
commonlinkratio_3                 0
commonlinkratio_4                 0
compression_ratio                 0
embed_ratio                       0
framebased                        0
frameTagRatio                     0
hasDomainLink                     0
html_ratio                        0
image_ratio                       0
is_news                           0
lengthyLinkDomain                 0
linkwordscore                     0
news_front_page                   0
non_markup_alphanum_characters    0
numberOfLinks                     0
numwords_in_url                   0
parametrizedLinkRatio             0
spelling_errors_ratio             0
label                             0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder


In [6]:
le= LabelEncoder()

In [7]:
train['url']= le.fit_transform(train['url'].values)
train['boilerplate']= le.fit_transform(train['boilerplate'].values)
train['alchemy_category']= le.fit_transform(train['alchemy_category'].values)
train['alchemy_category_score']= le.fit_transform(train['alchemy_category_score'].values)
train['is_news']= le.fit_transform(train['is_news'].values)
train['news_front_page']= le.fit_transform(train['news_front_page'].values)

In [8]:
train

url  urlid  ...  spelling_errors_ratio  label
0     3097   4042  ...               0.079130      0
1     5938   8471  ...               0.125448      1
2     5327   1164  ...               0.057613      1
3     3674   6684  ...               0.100858      1
4      359   9006  ...               0.082569      0
...    ...    ...  ...                    ...    ...
7390  2364   8958  ...               0.071429      0
7391  6878   8895  ...               0.109453      0
7392   849   1191  ...               0.117647      1
7393  1666   5612  ...               0.333333      1
7394  2160     90  ...               0.134146      0

[7395 rows x 27 columns]

In [9]:
l1= list(train['framebased'])
l2= list(train['hasDomainLink'])


In [10]:
l1

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [11]:
df= train.pop('framebased')

In [12]:
df

0       0
1       0
2       0
3       0
4       0
       ..
7390    0
7391    0
7392    0
7393    0
7394    0
Name: framebased, Length: 7395, dtype: int64

In [13]:
train

url  urlid  ...  spelling_errors_ratio  label
0     3097   4042  ...               0.079130      0
1     5938   8471  ...               0.125448      1
2     5327   1164  ...               0.057613      1
3     3674   6684  ...               0.100858      1
4      359   9006  ...               0.082569      0
...    ...    ...  ...                    ...    ...
7390  2364   8958  ...               0.071429      0
7391  6878   8895  ...               0.109453      0
7392   849   1191  ...               0.117647      1
7393  1666   5612  ...               0.333333      1
7394  2160     90  ...               0.134146      0

[7395 rows x 26 columns]

In [14]:
train.isnull().sum()

url                               0
urlid                             0
boilerplate                       0
alchemy_category                  0
alchemy_category_score            0
avglinksize                       0
commonlinkratio_1                 0
commonlinkratio_2                 0
commonlinkratio_3                 0
commonlinkratio_4                 0
compression_ratio                 0
embed_ratio                       0
frameTagRatio                     0
hasDomainLink                     0
html_ratio                        0
image_ratio                       0
is_news                           0
lengthyLinkDomain                 0
linkwordscore                     0
news_front_page                   0
non_markup_alphanum_characters    0
numberOfLinks                     0
numwords_in_url                   0
parametrizedLinkRatio             0
spelling_errors_ratio             0
label                             0
dtype: int64

In [15]:
x= train.iloc[:,0:25]
y= train['label']

In [16]:
x

url  urlid  ...  parametrizedLinkRatio  spelling_errors_ratio
0     3097   4042  ...               0.152941               0.079130
1     5938   8471  ...               0.181818               0.125448
2     5327   1164  ...               0.166667               0.057613
3     3674   6684  ...               0.041667               0.100858
4      359   9006  ...               0.098765               0.082569
...    ...    ...  ...                    ...                    ...
7390  2364   8958  ...               0.040404               0.071429
7391  6878   8895  ...               0.020000               0.109453
7392   849   1191  ...               0.434211               0.117647
7393  1666   5612  ...               0.026316               0.333333
7394  2160     90  ...               0.005917               0.134146

[7395 rows x 25 columns]

In [17]:
y

0       0
1       1
2       1
3       1
4       0
       ..
7390    0
7391    0
7392    1
7393    1
7394    0
Name: label, Length: 7395, dtype: int64

In [18]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_scaled= sc.fit_transform(x)

In [19]:
x_scaled

array([[-0.28106301, -0.41457706, -0.32952424, ...,  0.94013354,
        -0.10870584, -0.27883964],
       [ 1.04977036,  1.03842208,  0.63422556, ...,  1.24945404,
         0.04885672,  0.3058009 ],
       [ 0.76355452, -1.35874764, -0.58533727, ...,  1.86809504,
        -0.03381499, -0.5504239 ],
       ...,
       [-1.33411244, -1.34988989,  0.52178028, ...,  0.01217204,
         1.42599342,  0.20733554],
       [-0.9513983 ,  0.10048473, -0.0179571 , ..., -1.53443045,
        -0.79961612,  2.92976964],
       [-0.71998975, -1.71108927, -0.70527891, ..., -0.29714846,
        -0.91091784,  0.41559268]])

In [20]:
from sklearn.model_selection import train_test_split 

In [21]:
x_train,x_val,y_train,y_val = train_test_split(x_scaled,y,test_size=0.2)

DECISION TREE

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
Dt= DecisionTreeClassifier()
Dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [24]:
print('Training accuracy:', Dt.score(x_train,y_train))

Training accuracy: 1.0


In [25]:
Dt.score(x_val,y_val)

0.6206896551724138

In [26]:
from sklearn.metrics import confusion_matrix, classification_report

In [27]:
import numpy as np
p= Dt.predict(x_val)

print(confusion_matrix(y_val,p))

[[415 295]
 [266 503]]


In [28]:
p

array([1, 1, 1, ..., 1, 0, 1])

In [29]:
print(classification_report(y_val,p))

              precision    recall  f1-score   support

           0       0.61      0.58      0.60       710
           1       0.63      0.65      0.64       769

    accuracy                           0.62      1479
   macro avg       0.62      0.62      0.62      1479
weighted avg       0.62      0.62      0.62      1479



RANDOM FOREST

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
model= RandomForestClassifier(n_estimators= 50, random_state= 42)
model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [32]:
print('Training accuracy:', model.score(x_train,y_train))

Training accuracy: 0.9998309668695065


In [33]:
model.score(x_val,y_val)

0.6930358350236646

In [34]:
p1= model.predict(x_val)
print(confusion_matrix(y_val,p1))

[[491 219]
 [235 534]]


In [35]:
print(classification_report(y_val,p1))

              precision    recall  f1-score   support

           0       0.68      0.69      0.68       710
           1       0.71      0.69      0.70       769

    accuracy                           0.69      1479
   macro avg       0.69      0.69      0.69      1479
weighted avg       0.69      0.69      0.69      1479



SVM

In [36]:
from sklearn.svm import SVC
model_svm= SVC()
model_svm.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:

print('Training accuracy:', model_svm.score(x_train,y_train))

Training accuracy: 0.731237322515213


In [38]:
model_svm.score(x_val,y_val)

0.6659905341446923

In [39]:
p3= model_svm.predict(x_val)
print(confusion_matrix(y_val,p3))

[[453 257]
 [237 532]]


In [40]:
print(classification_report(y_val,p3))

              precision    recall  f1-score   support

           0       0.66      0.64      0.65       710
           1       0.67      0.69      0.68       769

    accuracy                           0.67      1479
   macro avg       0.67      0.66      0.67      1479
weighted avg       0.67      0.67      0.67      1479



KNN

In [41]:
from sklearn.neighbors import KNeighborsClassifier
model_knn= KNeighborsClassifier()
model_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [42]:
print('Training accuracy:', model_knn.score(x_train,y_train))

Training accuracy: 0.7596348884381339


In [43]:
model_knn.score(x_val,y_val)

0.6247464503042597

In [44]:
p2= model_knn.predict(x_val)
print(confusion_matrix(y_val,p2))

[[381 329]
 [226 543]]


In [45]:
print(classification_report(y_val,p2))

              precision    recall  f1-score   support

           0       0.63      0.54      0.58       710
           1       0.62      0.71      0.66       769

    accuracy                           0.62      1479
   macro avg       0.63      0.62      0.62      1479
weighted avg       0.63      0.62      0.62      1479



In [46]:
test= pd.read_csv('/content/test.tsv', delimiter= '\t')
test.head()

url  ...  spelling_errors_ratio
0  http://www.lynnskitchenadventures.com/2009/04/...  ...               0.080597
1            http://lolpics.se/18552-stun-grenade-ar  ...               0.176471
2  http://www.xcelerationfitness.com/treadmills.html  ...               0.125000
3  http://www.bloomberg.com/news/2012-02-06/syria...  ...               0.063126
4  http://www.wired.com/gadgetlab/2011/12/stem-tu...  ...               0.065341

[5 rows x 26 columns]

In [47]:
test

url  ...  spelling_errors_ratio
0     http://www.lynnskitchenadventures.com/2009/04/...  ...               0.080597
1               http://lolpics.se/18552-stun-grenade-ar  ...               0.176471
2     http://www.xcelerationfitness.com/treadmills.html  ...               0.125000
3     http://www.bloomberg.com/news/2012-02-06/syria...  ...               0.063126
4     http://www.wired.com/gadgetlab/2011/12/stem-tu...  ...               0.065341
...                                                 ...  ...                    ...
3166  http://busy-mommy.com/2012/02/peep-brownie-smo...  ...               0.063401
3167  http://www.cannabissearch.com/edibles/cheesecake/  ...               0.061995
3168  http://www.tastespotting.com/popular/views/all...  ...               0.117647
3169  http://lifehacker.com/5839197/how-to-get-a-ful...  ...               0.111966
3170  http://www.howsweeteats.com/2011/03/crispy-par...  ...               0.130024

[3171 rows x 26 columns]

In [48]:
test['url']= le.fit_transform(test['url'].values)
test['boilerplate']= le.fit_transform(test['boilerplate'].values)
test['alchemy_category']= le.fit_transform(test['alchemy_category'].values)
test['alchemy_category_score']= le.fit_transform(test['alchemy_category_score'].values)
test['is_news']= le.fit_transform(test['is_news'].values)
test['news_front_page']= le.fit_transform(test['news_front_page'].values)

In [49]:
test

url  urlid  ...  parametrizedLinkRatio  spelling_errors_ratio
0     2257   5865  ...               0.242647               0.080597
1      659    782  ...               0.128205               0.176471
2     3093   6962  ...               0.581197               0.125000
3     1345   7640  ...               0.038835               0.063126
4     3056   3589  ...               0.096774               0.065341
...    ...    ...  ...                    ...                    ...
3166   277   7264  ...               0.012987               0.063401
3167  1398   9714  ...               0.333333               0.061995
3168  2788   5903  ...               0.177083               0.117647
3169   647   3176  ...               0.333333               0.111966
3170  1986   7441  ...               0.287154               0.130024

[3171 rows x 26 columns]

In [50]:
test.pop('framebased')

0       0
1       0
2       0
3       0
4       0
       ..
3166    0
3167    0
3168    0
3169    0
3170    0
Name: framebased, Length: 3171, dtype: int64

In [51]:
test

url  urlid  ...  parametrizedLinkRatio  spelling_errors_ratio
0     2257   5865  ...               0.242647               0.080597
1      659    782  ...               0.128205               0.176471
2     3093   6962  ...               0.581197               0.125000
3     1345   7640  ...               0.038835               0.063126
4     3056   3589  ...               0.096774               0.065341
...    ...    ...  ...                    ...                    ...
3166   277   7264  ...               0.012987               0.063401
3167  1398   9714  ...               0.333333               0.061995
3168  2788   5903  ...               0.177083               0.117647
3169   647   3176  ...               0.333333               0.111966
3170  1986   7441  ...               0.287154               0.130024

[3171 rows x 25 columns]

In [52]:
test.isna().sum()

url                               0
urlid                             0
boilerplate                       0
alchemy_category                  0
alchemy_category_score            0
avglinksize                       0
commonlinkratio_1                 0
commonlinkratio_2                 0
commonlinkratio_3                 0
commonlinkratio_4                 0
compression_ratio                 0
embed_ratio                       0
frameTagRatio                     0
hasDomainLink                     0
html_ratio                        0
image_ratio                       0
is_news                           0
lengthyLinkDomain                 0
linkwordscore                     0
news_front_page                   0
non_markup_alphanum_characters    0
numberOfLinks                     0
numwords_in_url                   0
parametrizedLinkRatio             0
spelling_errors_ratio             0
dtype: int64

In [60]:
model_svm.predict(test)

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
p= model.predict(test)

In [61]:
data = {'urlid': list(test['urlid']), 
        'label': list(model_svm.predict(test))}
df= pd.DataFrame(data)
df     

urlid  label
0      5865      0
1       782      0
2      6962      0
3      7640      0
4      3589      0
...     ...    ...
3166   7264      0
3167   9714      0
3168   5903      0
3169   3176      0
3170   7441      0

[3171 rows x 2 columns]

In [62]:
df.to_csv('sub.csv',index= False)